const {
  FRONTENT_DOMAIN,
  PORT,
  DATABASE_URI,
  SECRETE_KEY,
  ADMIN_USERNAME,
  ADMIN_PASSWORD,
  ADMIN_EMAIL,
  MAILER_EMAIL,
  MAILER_PASSWORD,
} = process.env;

module.exports = {
  PORT: PORT || 5000,
  FRONTENT_DOMAIN,
  DATABASE_URI,
  SECRETE_KEY,
  ADMIN_PASSWORD,
  ADMIN_USERNAME,
  ADMIN_EMAIL,
  MAILER_EMAIL,
  MAILER_PASSWORD,
};
