export default {
  //auth

  LOADED_USER: 'LOADED_USER',
  LOADED_USER_FAILED: 'LOADED_USER_FAILED',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGOUT: 'LOGOUT',
  UPDATE_USER: 'UPDATE_USER',
  // admin
  GET_LIST_USER: 'GET_LIST_USER',
};
